"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['run.py']
DATA_FILES = ['images']
OPTIONS = {'argv_emulation': False,
    'includes': ['indicate', 'AppKit'],
    'excludes': [
        'PyQt4.QtDeclarative',
        'PyQt4.QtHelp',
        'PyQt4.QtDesigner',
        'PyQt4.QtMultimedia',
        'PyQt4.QtNetwork',
        'PyQt4.QtOpenGL',
        'PyQt4.QtScript',
        'PyQt4.QtScriptTools',
        'PyQt4.QtSql',
        'PyQt4.QtSvg',
        'PyQt4.QtTest',
        'PyQt4.QtWebKit',
        'PyQt4.QtXml',
        'PyQt4.QtXmlPatterns',
        ],
        'plist': {
            'LSUIElement': True,
            'CFBundleName':'Jenkinz',
            'CFBundleDisplayName': 'Jenkinz'
            }
    # 'ISBackgroundOnly': True
    }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
